<h2 class="about-us-title fun-facts">Fun Facts</h2>

            <table>
                <thead>
                    <tr>
                        <th><em>Name</em></th>
                        <th><em>Dream Job</em></th>
                        <th><em>Coding Snack</em></th>
                        <th><em>Hometown</em></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Elias</td>
                        <td>Indefinite Vacation</td>
                        <td>Red Frogs</td>
                        <td>Uvira, Congo</td>
                    </tr>
                    <tr>
                        <td>Mahin</td>
                        <td>Data Analyst</td>
                        <td>Popcorn</td>
                        <td>Melbourne</td>
                    </tr>
                    <tr>
                        <td>Mohammad Maruf Haider</td>
                        <td>Mechatronics Engineer</td>
                        <td>Mineral water</td>
                        <td>Narayanganj, Bangladesh</td>
                    </tr>
                </tbody>
            </table>