<footer>
        <section class="ending-section">
            <div class="ending-container">
                <div class="ending-container-left-part">
                    <div class="company-logo">
                        <img src="assets/niwslogonb.png" alt="icon of globe">
                    </div>
    
                    <p class="site-title ending-title">N I W S</p>
                </div>
                <p class="repo-text">Github link: <a href="https://github.com/Emajaliwa/RecruitmentWebsite.git"
                        class="hyperlink">click here!</a></p>
    
    
    
            </div>
    
    
    
    
    
        </section>
    
    
    </footer>