<header class="hero-section">
        <nav class="nav-bar">
    
            <div style="display: flex; align-items: center;">
                <div class="company-logo">
                    <img src="assets/niwslogonb.png" alt="icon of globe">
                </div>
    
                <p class="site-title">N I W S</p>
            </div>
    
            <div style="display: flex; align-items: center;">
                <ul class="nav-list">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="jobs.html">Jobs</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="apply.html">Apply</a></li>
                </ul>
    
                <div class="nav-menu">
                    <img src="assets/bars-solid-full.svg" alt="icon of globe">
                </div>
    
            </div>
    
        </nav>
    
    
        <div class="hero-text-section">
            <h1 class="hero-phrase">About <span style="color: #ff4c4c;">Us</span></h1>

            <figure class="group-photo">
                <img src="assets/IMG_8348.webp">
                <figcaption>Our great team!</figcaption>
            </figure>

            

    
    
    
        </div>
    
    
    </header>